apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
stringData:
  username: "${GITEA_ADMIN_USER}"
  password: "${GITEA_ADMIN_PASSWORD}"
  email: "${GITEA_ADMIN_EMAIL}"
  bindDn: "${GITEA_LDAP_DN}"
  bindPassword: "${GITEA_LDAP_PASSWORD}"