apiVersion: v1
kind: Secret
metadata:
  name: ldap-credentials
  namespace: auth
stringData:
  LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
  LDAP_CONFIG_ADMIN_PASSWORD: "${LDAP_CONFIG_ADMIN_PASSWORD}"