---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    grafana-admin-password: AgCk4lTvFS4HgO38nypUyIiQhAW7YBTCrC1de92uepok3mnbJ2aIXoFvvW5HddjYQrIOTP3o0Xxlf2A0tdMYcTjPekgGjxdUQuoOoh749fmShRCfJdRBPUHVnYKIsayjxQsXySZ8QhgKHnk6KBjr+RT6SmXTgffT50+/Nl9aHH01sUm6DrEQZhPuQauWXQSnxSe78alm26znTeF6GmZU3sN3WNunboc4GkHwG3G/4jqsOYCEfc1TF4vp7B+yny2LwGJN2pfW2IrrMRCg5RaLDPZi9O2ZhFtlvhEm0WXvOpszQGlYJpt75CAD2DME5CvhxeDlZZTZ3q/PkIzP6sg4wOKpwPSeKPmi4+mQWKmD6o8k7Kjth0IDAC5HUFWoKbwQAhnD63rmtAENFBxSQbq1YF3+AJCKWZRmPXY213t1Pc0c9x7kDY+F1BR5Mpx+uSvqMCbM2wrTurikZbJs2uXuboHoa9eCmRERgsdpysBMGeI4ujOC4YqcQ2nVtdFdqnpn8Y0ITUYhI0ybUnaaja7yy3aDqLxcJ9bKMXixzueocGbj758eweaBkOZZZWneyAFPMVk1as1kYsVvGRh/62pYNVRahj50SLSxxHsJ3aT1ZAr/D+ev2bj/bNevzdPcTGmGB6ueZRxLHvmak/yPusBGQFuSuK+CHD0ctxqo+NNYPHR1srxLAZY6e0sQ+d7Bog1X7oQdg3Mn
    grafana-admin-user: AgAgq37InrLhF5+YPzMAB9TGxhdLsLLBap1o8Q6Z9mVU2sN+UKXS+4u+1lf3Sc1l2nqFF1BCEi6I6kYtweJ0utnuGmZZvQD0R86QK+f8wA6rp4eErmqtmL+fLrHhgnYSz8m+2wJe11QVieMtJqpNluJgHz9fE7HIBIrEf9l5tY08GxuUFeEMwNHA3L31IASYqDNWygUDZ4u+Y0yIpDVlJB19OJQa4PXJw2Yrl9Bx3aTAPWqwrAJqJ77t6HYGLIHgv8skFHx/3c81uzWaKWFgfMF0vwgZMtDmwK7ilE4pz1Zvdz+C4mJJ5zWFUQZ3++NQmFUlNbn4T1BRKNeEeXmq6mPqj5BaPfVa9f7J0N8YeF34kJif6ErEduKpYYfRUDT+12cMt3+Sg1prLEjYeDftsc0CGceqOZFv/C/wlgEA7d0viclATMJyh7CWKmt9bXgjerEQpBtg2c9xndWGWjbfPCcn7udsiXTAOYblzMNH85WOosxmEgZB/qVpFaxgkSkLDI/FszdHSfS3Td8NDcynmOXUfN7z7+EZ6IqSTQw9Ipgsd9Ds7s96Y2ruyR6cxgOcaZDmqiwoFhJ3LYdyRxH8SOCua/S9rjYr6ijafsXntYNqWrnhWLJnyP3zk3Wg5MZL9+8ZXuIdkzTbdx1/hfHsnqM09OKPt7ghrvGXtOkgtJq7GTFQZkclaXvAWXW4c3lpJi14SOdl
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
